services:
  - type: web  # ← ✅ Needs to be 'web' for webhooks
    name: telegram-referral-bot
    env: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromEnvVar: TELEGRAM_BOT_TOKEN
      - key: CASHFREE_APP_ID
        fromEnvVar: CASHFREE_APP_ID
      - key: CASHFREE_SECRET_KEY
        fromEnvVar: CASHFREE_SECRET_KEY
      - key: DATABASE_URL
        fromEnvVar: DATABASE_URL
